jobs:
  setup:
    docker:
      - image: cimg/node:14.15.4-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  ci:
    jobs:
      - setup
